### ISSUE TITLE
Regarding dataset IIRC

### ISSUE THREAD

**Issue by yc-song** [canghongjian/beam_retriever#10]
Hi. Thanks for your interesting work.

I'm wondering if you can provide a minimal guideline for running your codebase on IIRC dataset (appendix D)

Also, I'm curious if the result from appendix D is applied to the official IIRC dataset or you went through another pre-processing.

Best regards.

**Comment by canghongjian** [comment]
Hello, thanks for your interest in our work! You should preprocess the original IIRC dataset using the method mentioned in Appendix D (more specifically, we follow the steps in [IRCOT](https://github.com/StonyBrookNLP/ircot) ), then you can train Beam Retrieval by editing the dataset_type in the bash file. The Retrieval EM is calculated in the same way as MuSiQue because the preprocessed IIRC shares the same format with MuSiQue.

**Comment by yc-song** [comment]
Everything clear. Thanks.
