### ISSUE TITLE
query with Beam Retrieval of other datasets

### ISSUE THREAD

**Issue by codefreshman1024** [canghongjian/beam_retriever#3]
Hi,bro!
I want to use Beam Retrieval in my model,which test in other KGQA datasets,such as WebQSP or CWQ.
So I ask about compatibility this way in other datasets.Thanks!

**Comment by canghongjian** [comment]
> Hi,bro! I want to use Beam Retrieval in my model,which test in other KGQA datasets,such as WebQSP or CWQ. So I ask about compatibility this way in other datasets.Thanks!

Hello @codefreshman1024 ! Sorry for the late reply. Beam Retrieval mainly focuses on the unstructured multi-hop QA datasets, and I'm not sure whether it could be applied to structured datasets such as KGQA. Maybe you can try to transform the structured data into unstructured form. In general, I don't recommend doing this because there are more suitable papers and methods in the KGQA field.

**Comment by codefreshman1024** [comment]
Thank you for your suggestion!I understand that the beam retrieval method used in your paper is used to supervise the intermediate process, so that it can better find the target entity. I think it is the same for text or structured data sets, and I am also actively looking for other supervision methods

**Comment by canghongjian** [comment]
Your understanding is correct, and applying the idea of beam retrieval to KGQA is promising. I hope you can make a progress. Feel free to contact me if you have other questions.

**Comment by codefreshman1024** [comment]
Ok, I first want to know if this beam retrieval method is used as a module to participate in the QA, so that we can only change the input and output format, otherwise it is a lot of work.

**Comment by canghongjian** [comment]
Yes. Beam Retrieval is used for selecting relevant passages given a question and a set of candidate passages. If you can generate this type of format, then you can use Beam Retrieval.
